models/Product.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 5/27/2018
 * Time: 17:00
 */

namespace app\models;


use app\modules\admin\models\Comment;
use yii\db\ActiveRecord;

class Product extends ActiveRecord
{
    public $comment;

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }

    public static function tableName()
    {
        return 'product';
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }






}

controllers/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 5/30/2018
 * Time: 21:24
 */

namespace app\controllers;


use yii\web\Controller;
use app\models\Cart;
use app\models\Product;
use Yii;
use app\models\OrderItems;
use app\models\Order;

class CartController extends Controller
{
    public function actionAdd()
    {
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $itemCount = !$qty ? 1 : $qty;
        $product = Product::findOne($id);
        if (empty($product)) return false;
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product,$itemCount);

        if (!Yii::$app->request->isAjax) {
            return $this->redirect(Yii::$app->request->referrer);
        }

        $this->layout = false;
        return $this->render('cart', compact('session'));
    }

    public function actionClear()
    {
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.count');
        $session->remove('cart.sum');
        $this->layout = false;
        return $this->render('cart', compact('session'));

    }

    public function actionDellItem()
    {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalculation($id);

        $this->layout = false;
        return $this->render('cart', compact('session'));
    }

    public function actionShowCart()
    {
        $session = Yii::$app->session;
        $session->open();

        $this->layout = false;
        return $this->render('cart', compact('session'));
    }

    public function actionView()
    {
        $session = Yii::$app->session;
        $session->open();
        $order = new Order();
        if ($order->load(Yii::$app->request->post())) {
            $order->qty = $session['cart.count'];
            $order->sum = $session['cart.sum'];
            if ($order->save()) {
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Your order is accepted');
                //from user
                Yii::$app->mailer->compose('order', ['session' => $session])
                    ->setFrom(['sashanevirkovets@gmail.com'=> 'Shop manager'])
                    ->setTo($order->email)
                    ->setSubject('Order')
                    ->send();
                //from admin
                /*Yii::$app->mailer->compose('order', ['session' => $session])
                    ->setFrom(['sashanevirkovets@gmail.com'=> 'Shop manager'])
                    ->setTo(Yii::$app->params['adminEmail'])
                    ->setSubject('Order')
                    ->send();*/



                $session->remove('cart');
                $session->remove('cart.count');
                $session->remove('cart.sum');
                return $this->refresh();
            }else{
                Yii::$app->session->setFlash('error','error');
            }

        }
        return $this->render('view',compact('session','order'));
    }

    protected function saveOrderItems($items,$order_id)
    {
        foreach ($items as $id => $item) {
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['count'];
            $order_items->sum_item = $item['count'] * $item['price'];
            $order_items->save();


        }
    }

}

controllers/CategoryController.php
<?php

namespace app\controllers;

use yii\data\Pagination;
use yii\web\Controller;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\web\HttpException;

class CategoryController extends Controller
{
    public function actionIndex()
    {
        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();

        $this->setMetatag('SHOP');
        return $this->render('index',[
            'hits'=>$hits
        ]);
    }

    public function actionView($id)
    {
//        $products = Product::find()->where(['category_id' => $id])->all();
        $category = Category::findOne($id);
        if (empty($category)) {
            throw new HttpException(404,'The requested Item could not be found');
        }

        $query = Product::find()->where(['category_id' => $id]);
        $pages = new Pagination([
            'totalCount' => $query->count(),
            'forcePageParam' => false,
            'pageSizeParam' => false,
            'pageSize' => 3,

        ]);

        $products = $query->offset($pages->offset)->limit($pages->limit)->all();

        $this->setMetatag('Shop' . ' ' . $category->name,$category->keywords,$category->description);

        return $this->render('view', [
            'products' => $products,
            'category' => $category,
            'pages' => $pages,


        ]);
    }

    public function actionSearch()
    {
        $search = trim(Yii::$app->request->get('search'));
        if (!$search) {
            return $this->render('search');
        }
        $query = Product::find()->where(['like', 'name',$search]);
        $pages = new Pagination([
            'totalCount' => $query->count(),
            'forcePageParam' => false,
            'pageSizeParam' => false,
            'pageSize' => 3,

        ]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        return $this->render('search', [
            'products' => $products,
            'pages' => $pages,
            'search' => $search,

        ]);

    }

    protected function setMetatag($title = null, $keywords = null, $description = null)
    {
        $this->view -> title = $title;
        $this->view ->registerMetaTag([
            'name'=>'keywords', 'content' => "$keywords",

        ]);
        $this->view ->registerMetaTag([
            'name'=>'description', 'content' => "$description",

        ]);
    }

}

controllers/CommentController.php
<?php

namespace app\controllers;

use Yii;
use app\modules\admin\models\Comment;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CommentController implements the CRUD actions for Comment model.
 */
class CommentController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    public function actionCreate()
    {
        $model = new Comment();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Comment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Comment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id,$product_id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['/product/view','id'=>$product_id]);
    }

    /**
     * Finds the Comment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Comment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comment::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 5/30/2018
 * Time: 10:26
 */

namespace app\controllers;

use yii\data\ActiveDataProvider;

use app\models\CommentForm;
use app\models\Product;
use app\models\User;
use app\modules\admin\models\Comment;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\HttpException;

class ProductController extends Controller
{
    public function actionView($id)
    {
        $product = Product::findOne($id);
        //$comments = Comment::find()->with('comments')->where(['product_id' => $id])->all();
        $commentForm = new CommentForm();



        $query = Comment::find()->with('comments')->where(['product_id' => $id]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 5]);
        $comments = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();




        if (empty($product)) {
            throw new HttpException(404,'The requested Item could not be found');
        }
        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();


        $dataProvider = new ActiveDataProvider([
            'query' => Comment::find()->where(['product_id'=>$id])->orderBy('date DESC'),
            'pagination' => [
                'pageSize' => 5,

            ],
        ]);



        return $this->render('view',[
            'product' => $product,
            'hits' => $hits,
            'comments' => $comments,
            'commentForm' => $commentForm,
            'pages' => $pages,
            'dataProvider' => $dataProvider,



        ]);

    }


}

views/product/view.php
<?php

use nirvana\infinitescroll\InfiniteScrollPager;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use yii\widgets\LinkPager;
use yii\widgets\ListView;

$this->title = 'Shop' . ' ' . $product->name;
$this->params['breadcrumbs'][] = $this->title;
?>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>
                    <ul class="catalog category-products">
                        <?= \app\components\MenuWidget::widget(['frontend' => 'menu']) ?>
                    </ul>

                    <div class="brands_products"><!--brands_products-->
                        <h2>Brands</h2>
                        <div class="brands-name">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                                <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                                <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                                <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                                <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                                <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                                <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
                            </ul>
                        </div>
                    </div><!--/brands_products-->

                    <div class="price-range"><!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well">
                            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                            <b>$ 0</b> <b class="pull-right">$ 600</b>
                        </div>
                    </div><!--/price-range-->

                    <div class="shipping text-center"><!--shipping-->
                        <img src="/images/home/shipping.jpg" alt="" />

                    </div><!--/shipping-->

                </div>
            </div>


            <?php
            $mainImg = $product->getImage();
            $gallery = $product->getImages();


            ?>
            <div class="col-sm-9 padding-right">
                <div class="product-details"><!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">
                            <?= Html::img($mainImg->getUrl(350),  ['alt'=>$product->name]) ?>
                        </div>
                        <div id="similar-product" class="carousel slide" data-ride="carousel">

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner">
                                <?php $count = count($gallery); $i = 0; foreach($gallery as $img): ?>
                                    <?php if($i % 3 == 0):?>
                                        <div class="item <?php if($i == 0) echo ' active'?>">
                                    <?php endif;?>
                                        <a href=""><?= Html::img($img->getUrl("85x84"), ['alt' => $product->name]) ?></a>
                                    <?php $i++; if($i % 3 == 0 || $i == $count):?>
                                        </div>
                                    <?php endif;?>
                                <?php endforeach;?>
                            </div>

                            <!-- Controls -->
                            <a class="left item-control" href="#similar-product" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right item-control" href="#similar-product" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>

                    </div>
                    <div class="col-sm-7">
                        <div class="product-information"><!--/product-information-->
                            <?php if ($product->new) : ?>
                                <?= Html::img('@web/images/home/new.png',['alt'=>'new','class'=> 'new']) ?>
                            <?php endif; ?>
                            <?php if ($product->sale) : ?>
                                <?= Html::img('@web/images/home/sale.png',['alt'=>'sale','class'=> 'new']) ?>
                            <?php endif; ?>
                            <h2><?= $product->name; ?></h2>
<!--                            <p>Web ID: 1089772</p>-->
<!--                            <img src="/images/product-details/rating.png" alt="" />-->
                            <span>
									<span>US $ <?= $product->price ?></span>
									<label>Quantity:</label>
									<input type="text" value="1" min="1" id="qty" />
									<a  href="<?= Url::to(['cart/add','id'=>$product->id]) ?>" data-id="<?= $product->id ?>" class="btn btn-default cart add-to-cart">
										<i class="fa fa-shopping-cart"></i>
										Add to cart
									</a>
								</span>
                            <!--<p><b>Availability:</b> In Stock</p>
                            <p><b>Condition:</b> New</p>-->

                            <hr>
                            <p><b>Brand:</b> <a href="<?= \yii\helpers\Url::to(['category/view','id'=>$product->category->id]) ?>"><?= $product->category->name ?></a></p>
                            <hr>
                            <p><?= $product->content ?></p>
                            <a href=""><img src="/images/product-details/share.png" class="share img-responsive"  alt="" /></a>
                        </div><!--/product-information-->
                    </div>
                </div><!--/product-details-->

                <div class="row">
                    <?php foreach ($comments as $comment) :?>

                <div class="tab-pane fade active in" id="reviews" >
                    <div class="col-sm-12">
                        <ul>
<!--                            <li><a href=""><i class="fa fa-user"></i>--><?//= $comment->user_id ?><!--</a></li>-->
                            <li><span><i class="fa fa-user"></i><?= $comment->user->username ?></span></li>
                            <li><span><i class="fa fa-clock-o"></i><?= $comment->date ?></span></li>
<!--                            <li><a href=""><i class="fa fa-calendar-o"></i>31 DEC 2014</a></li>-->
                        </ul>
                        <p><?= $comment->text; ?></p>

                        <?php $date = $comment->date;
                        $commentDate = strtotime($date);
                        $futureDate = $commentDate+(60*5);
                        $formatDate = date("Y-m-d H:i:s", $futureDate);
                        ?>

                        <?php if (Yii::$app->user->id == $comment->user_id && $formatDate >= date('Y-m-d H:i:s')) :?>
                        <?=  Html::a('Delete', ['comment/delete', 'id' => $comment->id,'product_id'=>$product->id], [
                            'class' => 'text-danger',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]) ?>


                        <?php endif; ?>

                    </div>
                </div>
                    <?php endforeach; ?>
                </div>

              <?php
              echo LinkPager::widget([
                    'pagination' => $pages,

                ]);


              ?>








                <div class="row">
                    <div class="col-sm-12">
                        <hr>
                <?php $form = ActiveForm::begin([
                        'action' => ['site/comment','id'=>$product->id]
                ])?>

                <?= $form->field($commentForm,'comment')->textarea(['class'=>'form-control','placeholder'=> 'write comment'])->label(false)?>

                <button type="submit" class="btn send-btn">Post Comment</button>
                <?php ActiveForm::end() ?>
                    </div>
                </div>







                <div class="recommended_items"><!--recommended_items-->
                    <h2 class="title text-center">recommended items</h2>

                    <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">

                            <?php $count  = count($hits);$i = 0;
                            foreach ( $hits as $hit) : ?>
                                <?php if ($i % 3 == 0) : ?>
                            <div class="item <?php if ($i == 0) echo 'active'?>">
                                <?php endif; ?>
                                <div class="col-sm-4">
                                    <div class="product-image-wrapper">
                                        <div class="single-products">
                                            <div class="productinfo text-center">
                                                <?= Html::img('@web/images/products/'. $hit->img, ['alt'=>$hit->name]) ?>
                                                <h2>$ <?= $hit->price; ?></h2>
                                                <p><a href="<?= Url::to(['product/view','id'=>$hit->id]) ?>"><?= $hit->name; ?></a></p>
                                                <button type="button" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php $i++; if ($i % 3 == 0 || $i == $count) : ?>

                            </div>

                            <?php endif; endforeach; ?>


                        </div>
                        <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div><!--/recommended_items-->

            </div>
        </div>
    </div>
</section>