models/Cart.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 5/30/2018
 * Time: 21:27
 */

namespace app\models;


use yii\base\Model;
use yii\db\ActiveRecord;

class Cart extends ActiveRecord
{
    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }
    public function addToCart($product, $count = 1)
    {

        $mainImg = $product->getImage();
        if (isset($_SESSION['cart'][$product->id])) {
            $_SESSION['cart'][$product->id]['count'] += $count;

        }else{
            $_SESSION['cart'][$product->id] = [
                'count' => $count,
                'name' => $product->name,
                'price' => $product->price,
                'img' => $mainImg->getUrl('x70'),


            ];
        }

        $_SESSION['cart.count'] = isset($_SESSION['cart.count']) ? $_SESSION['cart.count'] + $count : $count;
        $_SESSION['cart.sum'] = isset($_SESSION['cart.sum']) ? $_SESSION['cart.sum']  + $count *  $product->price : $count * $product->price;
    }

    public function recalculation($id)
    {
        if (!isset($_SESSION['cart'][$id])) return false;
        $newCount = $_SESSION['cart'][$id]['count'];
        $newSum = $_SESSION['cart'][$id]['count'] * $_SESSION['cart'][$id]['price'];

        $_SESSION['cart.count'] -= $newCount;
        $_SESSION['cart.sum'] -= $newSum;

        unset($_SESSION['cart'][$id]);
    }


}

controllers/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 5/30/2018
 * Time: 21:24
 */

namespace app\controllers;


use yii\web\Controller;
use app\models\Cart;
use app\models\Product;
use Yii;
use app\models\OrderItems;
use app\models\Order;

class CartController extends Controller
{
    public function actionAdd()
    {
        $id = Yii::$app->request->get('id');
        $qty = (int)Yii::$app->request->get('qty');
        $itemCount = !$qty ? 1 : $qty;
        $product = Product::findOne($id);
        if (empty($product)) return false;
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product,$itemCount);

        if (!Yii::$app->request->isAjax) {
            return $this->redirect(Yii::$app->request->referrer);
        }

        $this->layout = false;
        return $this->render('cart', compact('session'));
    }

    public function actionClear()
    {
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.count');
        $session->remove('cart.sum');
        $this->layout = false;
        return $this->render('cart', compact('session'));

    }

    public function actionDellItem()
    {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalculation($id);

        $this->layout = false;
        return $this->render('cart', compact('session'));
    }

    public function actionShowCart()
    {
        $session = Yii::$app->session;
        $session->open();

        $this->layout = false;
        return $this->render('cart', compact('session'));
    }

    public function actionView()
    {
        $session = Yii::$app->session;
        $session->open();
        $order = new Order();
        if ($order->load(Yii::$app->request->post())) {
            $order->qty = $session['cart.count'];
            $order->sum = $session['cart.sum'];
            if ($order->save()) {
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Your order is accepted');
                //from user
                Yii::$app->mailer->compose('order', ['session' => $session])
                    ->setFrom(['sashanevirkovets@gmail.com'=> 'Shop manager'])
                    ->setTo($order->email)
                    ->setSubject('Order')
                    ->send();
                //from admin
                /*Yii::$app->mailer->compose('order', ['session' => $session])
                    ->setFrom(['sashanevirkovets@gmail.com'=> 'Shop manager'])
                    ->setTo(Yii::$app->params['adminEmail'])
                    ->setSubject('Order')
                    ->send();*/



                $session->remove('cart');
                $session->remove('cart.count');
                $session->remove('cart.sum');
                return $this->refresh();
            }else{
                Yii::$app->session->setFlash('error','error');
            }

        }
        return $this->render('view',compact('session','order'));
    }

    protected function saveOrderItems($items,$order_id)
    {
        foreach ($items as $id => $item) {
            $order_items = new OrderItems();
            $order_items->order_id = $order_id;
            $order_items->product_id = $id;
            $order_items->name = $item['name'];
            $order_items->price = $item['price'];
            $order_items->qty_item = $item['count'];
            $order_items->sum_item = $item['count'] * $item['price'];
            $order_items->save();


        }
    }

}

controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 5/30/2018
 * Time: 10:26
 */

namespace app\controllers;

use yii\data\ActiveDataProvider;

use app\models\CommentForm;
use app\models\Product;
use app\models\User;
use app\modules\admin\models\Comment;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\HttpException;

class ProductController extends Controller
{
    public function actionView($id)
    {
        $product = Product::findOne($id);
        //$comments = Comment::find()->with('comments')->where(['product_id' => $id])->all();
        $commentForm = new CommentForm();



        $query = Comment::find()->with('comments')->where(['product_id' => $id]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 5]);
        $comments = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();




        if (empty($product)) {
            throw new HttpException(404,'The requested Item could not be found');
        }
        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();


        $dataProvider = new ActiveDataProvider([
            'query' => Comment::find()->where(['product_id'=>$id])->orderBy('date DESC'),
            'pagination' => [
                'pageSize' => 5,

            ],
        ]);



        return $this->render('view',[
            'product' => $product,
            'hits' => $hits,
            'comments' => $comments,
            'commentForm' => $commentForm,
            'pages' => $pages,
            'dataProvider' => $dataProvider,



        ]);

    }


}

views/cart/cart.php
<?php use yii\helpers\Html;

if (!empty($session['cart'])) :?>
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>img</th>
                    <th>name</th>
                    <th>count</th>
                    <th>price</th>
                    <th>delete</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($session['cart'] as $id => $item) : ?>
                    <tr>
                        <td class="text-center"><?= Html::img($item['img'],['alt'=> $item['name'],'height' => 50] )?></td>
                        <td><?= $item['name'] ?></td>
                        <td><?= $item['count'] ?></td>
                        <td><?= $item['price'] ?></td>
                        <td><button class="btn btn-danger dell-item" data-id="<?= $id ?>">Delete</button></td>
                    </tr>
                <?php endforeach; ?>
                    <tr>
                        <td colspan="4">Count</td>
                        <td><?= $session['cart.count'] ?></td>
                    </tr>
                    <tr>
                        <td colspan="4">Sum</td>
                        <td><?= $session['cart.sum'] ?></td>
                    </tr>
            </tbody>
        </table>
    </div>

<?php else: ?>
    <h3>Cart is empty </h3>
<?php endif; ?>

views/cart/view.php
<?php

$this->title = 'Cart';
$this->params['breadcrumbs'][] = $this->title;

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

?>

<div class="container">
    <?php if (Yii::$app->session->hasFlash('success')): ?>
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <?= Yii::$app->session->getFlash('success'); ?>
    </div>
    <?php endif; ?>

    <?php if (Yii::$app->session->hasFlash('error')) :?>
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <?= Yii::$app->session->getFlash('error') ?>
        </div>
    <?php endif; ?>
   <? if (!empty($session['cart'])) :?>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th>img</th>
                    <th>name</th>
                    <th>count</th>
                    <th>price</th>
                    <th>sum</th>
                    <th>delete</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($session['cart'] as $id => $item) : ?>
                    <tr>
                        <td class="text-center"><?= Html::img($item['img'],['alt'=> $item['name'],'height' => 100] )?></td>
                        <td><a href="<?= Url::to(['product/view','id'=>$id]) ?>"><?= $item['name'] ?></a></td>
                        <td><?= $item['count'] ?></td>
                        <td><?= $item['price'] ?></td>
                        <td><?= $item['count']*$item['price'] ?></td>
                        <td><button class="btn btn-danger dell-item" data-id="<?= $id ?>">Delete</button></td>
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td colspan="5">Count</td>
                    <td><?= $session['cart.count'] ?></td>
                </tr>
                <tr>
                    <td colspan="5">Sum</td>
                    <td><?= $session['cart.sum'] ?></td>
                </tr>
                </tbody>
            </table>
        </div>
       <hr>
       <?php $form = ActiveForm::begin() ?>
            <?= $form->field($order, 'name') ?>
            <?= $form->field($order, 'email') ?>
            <?= $form->field($order, 'phone') ?>
            <?= $form->field($order, 'address') ?>
            <?= Html::submitButton('odrder',['class'=>'btn btn-success ']) ?>
       <?php ActiveForm::end() ?>
    <?php else: ?>
        <h3>Cart is empty </h3>
    <?php endif; ?>


</div>